SET search_path TO ecommerce; --to avoid writing ecommerce.<tablename>

-- 1. List all customers
SELECT user_id, name, email
FROM users
WHERE role = 'customer';

-- 2. Total number of products per category
SELECT c.category_name, COUNT(p.product_id) AS total_products
FROM categories c
LEFT JOIN products p
ON c.category_id = p.category_id
GROUP BY c.category_name
ORDER BY total_products DESC;

-- 3. Products with low stock (less than 20)
SELECT product_id, name, stock
FROM products
WHERE stock < 20
ORDER BY stock ASC;

-- 4. Total revenue generated by each user
SELECT u.name, SUM(o.total_amount) AS total_spent
FROM users u
JOIN orders o
ON u.user_id = o.user_id
GROUP BY u.name
ORDER BY total_spent DESC;

-- 5. Total revenue by order status
SELECT status, SUM(total_amount) AS total_revenue
FROM orders
GROUP BY status;

-- 6. Top 5 best-selling products
SELECT p.name, SUM(oi.quantity) AS total_sold
FROM order_items oi
JOIN products p
ON oi.product_id = p.product_id
GROUP BY p.name
ORDER BY total_sold DESC
LIMIT 5;

-- 7. Average product rating
SELECT p.name, ROUND(AVG(r.rating), 2) AS avg_rating
FROM products p
JOIN reviews r
ON p.product_id = r.product_id
GROUP BY p.name
ORDER BY avg_rating DESC;

-- 8. Customers who have never placed an order
SELECT u.user_id, u.name
FROM users u
LEFT JOIN orders o
ON u.user_id = o.user_id
WHERE o.order_id IS NULL
AND u.role = 'customer';

-- 9. Orders with more than one item
SELECT o.order_id, COUNT(oi.order_item_id) AS item_count
FROM orders o
JOIN order_items oi
ON o.order_id = oi.order_id
GROUP BY o.order_id
HAVING COUNT(oi.order_item_id) > 1;

-- 10. Monthly revenue report
SELECT
    DATE_TRUNC('month', created_at) AS month,
    SUM(total_amount) AS monthly_revenue
FROM orders
GROUP BY month
ORDER BY month;

-- 11. Most reviewed products
SELECT p.name, COUNT(r.review_id) AS total_reviews
FROM products p
LEFT JOIN reviews r
ON p.product_id = r.product_id
GROUP BY p.name
ORDER BY total_reviews DESC;

-- 12. Average order value
SELECT ROUND(AVG(total_amount), 2) AS average_order_value
FROM orders;

-- 13. Orders that were cancelled
SELECT order_id, user_id, total_amount
FROM orders
WHERE status = 'cancelled';

-- 14. Payment success rate
SELECT payment_status, COUNT(*) AS count
FROM payments
GROUP BY payment_status;

-- 15. Users who spent more than average
SELECT u.name, SUM(o.total_amount) AS total_spent
FROM users u
JOIN orders o
ON u.user_id = o.user_id
GROUP BY u.name
HAVING SUM(o.total_amount) >
       (SELECT AVG(total_amount) FROM orders);

-- 16. Products never ordered
SELECT p.product_id, p.name
FROM products p
LEFT JOIN order_items oi
ON p.product_id = oi.product_id
WHERE oi.order_item_id IS NULL;

-- 17. Order details with product names
SELECT
    o.order_id,
    u.name AS customer,
    p.name AS product,
    oi.quantity,
    oi.price
FROM orders o
JOIN users u ON o.user_id = u.user_id
JOIN order_items oi ON o.order_id = oi.order_id
JOIN products p ON oi.product_id = p.product_id
ORDER BY o.order_id;

-- 18. Total items sold per category
SELECT c.category_name, SUM(oi.quantity) AS total_items_sold
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
JOIN categories c ON p.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_items_sold DESC;

-- 19. Customers with highest average order value
SELECT u.name, ROUND(AVG(o.total_amount), 2) AS avg_order_value
FROM users u
JOIN orders o ON u.user_id = o.user_id
GROUP BY u.name
ORDER BY avg_order_value DESC;

-- 20. Products with highest revenue contribution
SELECT p.name, SUM(oi.quantity * oi.price) AS total_revenue
FROM order_items oi
JOIN products p ON oi.product_id = p.product_id
GROUP BY p.name
ORDER BY total_revenue DESC;
